spring:
  application:
    name: voip-service

server:
  port: 8080


  #INSERT INTO db_voip.users (ID, USERNAME, EMAIL, PHONE) VALUES (9, 'tazul', 'tazul@jotno.net', '01825711955');
  #INSERT INTO db_voip.devices (ID, USER_ID, DEVICE_TOKEN) VALUES (9, 9, 'dTE-AzJ8a0IxLCoAWdDNxr:APA91bFmm3aI4WvnaY_CzbEu1B9kRIGjDKb4CXYvOj5DtW8kKg7RfE6mrzjj-NJcJVXWsFW4hhZ8cQSm026_Ipp4WXwWvnAwawypr6OL3tCU24IBcKw2wZh2WKdFoCd2a9PzYRRNXZC9');

  #UPDATE db_voip.devices SET DEVICE_TOKEN = 'e4LjsLLlScyBMs4sVcD-hR:APA91bHHs6OCKJXg1c8OyLu16RmZ4Lm2hzV8yDvEY6w5yF_5A-5XG2T318oazcFajT4z3OhuQpeIRN12vI7iCaTVKDtg_VzN0q0auqkHh6Cj3eI3WTt-0W3xvVES8HocHqO4mbpook9k' WHERE USER_ID = 2;