DROP TABLE IF EXISTS devices;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(250) NOT NULL,
    EMAIL VARCHAR(250) NOT NULL,
    PHONE VARCHAR(250) NOT NULL
);


CREATE TABLE devices (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT,
    DEVICE_TOKEN TEXT,
    FOREIGN KEY (USER_ID) REFERENCES users(ID)
);